###
POST http://localhost:5000/companies
Content-Type: application/json

{
    "companyName": "SEP SR.L.",
    "vatNumber": "01052190491",
    "address": {
        "street": "Viale Carducci 180",
        "city": "Livorno",
        "postalCode": "57124",
        "province": "Livorno",
        "country": "Italy"
    },
    "email": "sepedilizi@gmail.com",
    "IBAN": "IT35Y0300203280455343217862"
}

###
GET http://localhost:5000/companies

###
GET http://localhost:5000/companies/678bc4eb6279e6af82fced28

###
PUT http://localhost:5000/companies/678bc4eb6279e6af82fced28
Content-Type: application/json

{
    "IBAN": "IT55V0300203280539916298675"
}

###
DELETE http://localhost:5000/companies/6782c4cb9b8090e8d2b5ebba