###
POST http://localhost:5000/companies
Content-Type: application/json

{
    "companyName": "SEP S.R.L.",
    "vatNumber": "01052190491",
    "address": {
        "street": "Viale Carducci 180",
        "city": "Livorno",
        "postalCode": "57124",
        "province": "Livorno",
        "country": "Italy"
    },
    "email": "sepedilizia@virgilio.it",
    "IBAN": "IT35Y0300203280455343217862"
}

###
GET http://localhost:5000/companies

###
GET http://localhost:5000/companies/67897dfbc172401d642ccf69

###
PUT http://localhost:5000/companies/6782c4cb9b8090e8d2b5ebba
Content-Type: application/json

{
    "IBAN": "IT55V0300203280539916298675"
}

###
DELETE http://localhost:5000/companies/6782c4cb9b8090e8d2b5ebba