###
GET http://localhost:5000/companies

###
GET http://localhost:5000/companies/6723406bbb730785d387c2dc

###
PUT http://localhost:5000/companies/6723406bbb730785d387c2dc
Content-Type: application/json

{
  "companyName": "Epicode N.Two"
}

###
POST http://localhost:5000/companies
Content-Type: application/json

{
  "companyName": "EpicodeSchool",
  "vatNumber": "IT12345678901",
  "address": {
    "street": "Via Roma, 123",
    "city": "Milano",
    "postalCode": "20100",
    "province": "MI",
    "country": "Italia"
  },
  "logo": "https://example.com/path/to/logo.jpg",
  "IBAN": "IT60X0542811101000000123456"
}

###
DELETE http://localhost:5000/companies/672340abbb730785d387c2e1