### REQUESTS ###

###
PATCH http://localhost:5000/api/v1/employee/67234b29bb730785d387c329/requests/6723cc6ea9980b2f1102c804
Content-Type: application/json

{
    "status": "approved"
}

###
POST http://localhost:5000/api/v1/employee/67234b29bb730785d387c329/requests
Content-Type: application/json 

{
    "startDate": 774032800000,
    "endDate": 774032800001,
    "type": "paid"
}

###
GET http://localhost:5000/requests

### REQUESTS ###
