###
POST http://localhost:5000/companies/672a3814cc7e11a01aa426d5/profile
Content-Type: application/json

{
    "name": "Giovanni",
    "surname": "Epicode",
    "email": "giovanniepicode@gmail.com",
    "password": "giovanniepicode",
    "birthday": 323752800110,
    "IBAN": "IT20Q0300203280561121424713",
    "TIN": "PTTFRE86H17E625S",
    "country": "Italia"
}

###
GET http://localhost:5000/companies/672340d0bb730785d387c2e3/profile

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "ruoccoenricoandrea@gmail.com",
    "password": "enricoandrea"
}

###
GET http://localhost:5000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzA4MTU1NjUsImV4cCI6MTczMDgxOTE2NX0.lmH8AdzFd6ZUwDKrTQ6YsA9iSJiedmmG6aOQPbqNA8Q



