###
POST http://localhost:5000/user
Content-Type: application/json

{
  "firstName": "Mario",
  "lastName": "Rossi",
  "email": "mario.rossi@example.com",
  "phone": "123456789",
  "isAdmin": false,
  "position": "Elettricista",
  "companyId": "678bc4eb6279e6af82fced28",
  "password": "password123"
}

###
POST http://localhost:5000/user
Content-Type: application/json

{
  "firstName": "Orazio",
  "lastName": "Rossi",
  "email": "orazio.rossi@example.com",
  "phone": "123456789",
  "isAdmin": true,
  "adminRole": "Direttore",
  "companyId": "678a94301b84e9ebffc7cf30",
  "password": "password123"
}

###
PUT http://localhost:5000/user/678bc5256279e6af82fced2f
Content-Type: application/json

{
 "position": "Idraulico"
}

###
DELETE http://localhost:5000/user/678d4a561a6ce1f69a4f45c5